### ISSUE TITLE
Missing Texture dependencies in plugin release. 

### ISSUE THREAD

**Issue by MacMiggity** [AppLovin/AppLovin-MAX-Godot#11]
### MAX Plugin Version

1.0.1

### Godot Version

4.1

### Device/Platform Info

In Editor

### Current Behavior

![image](https://github.com/AppLovin/AppLovin-MAX-Godot/assets/3011035/3ece2f3f-3234-47be-8342-0f8f1ab38a57)
Resources are missing (Textures folder and contents). 

### Expected Behavior

Applovin plugin examples should work with no errors. 

### How to Reproduce

Start a blank project, download the Applovin plugin from the Asset Lib. Attempt to open the Release/addons/applovin_max/example/main.tscn scene.

**Comment by christophercong** [comment]
@AdamMcCurdy Godot Asset Lib is pretty particular about how they want the git repo to look. I've submitted a new release to the Godot Asset Lib to fix this issue (pending approval).

In the meantime, you can drag in the `/addons`, `/ios`, `/android` folders in this repo to the `res://` folder in your project. It's the same assets that will be in the new asset lib release based off this commit (ddac851fe77e3b01970ca79c9fbf80b53f220294).

**Comment by christophercong** [comment]
Hi @AdamMcCurdy, version 1.0.1 of the plugin is now available on the Godot Asset Library

**Comment by MacMiggity** [comment]
👍
