### ISSUE TITLE
Unable to load plugin script

### ISSUE THREAD

**Issue by lettdev** [AppLovin/AppLovin-MAX-Godot#16]
### MAX Plugin Version

1.0.1

### Godot Version

4.1.1

### Device/Platform Info

No

### Current Behavior

Get an error when trying to enable the plugin

![image](https://github.com/AppLovin/AppLovin-MAX-Godot/assets/24779254/41114b6c-c393-4bbb-8173-064a8ee0006c)

### How to Reproduce

- Create a new blank project
- Copy the MAX plugin folders (addons, ios, android) to res://
- Tick the enable checkbox for AppLovinMAX plugin in Project Settings/Plugins

**Comment by christophercong** [comment]
@lettdev that file `applovin_max.gd` is named differently from our plugin one `AppLovinMAX.gd`. Can you verify it's the same file and/or share the file here?

**Comment by lettdev** [comment]
Turns out somehow the file plugin.cfg wasn't replaced and still the 1.0.0 version, which uses that file path (applovin_max.gd). I replace it now but has another error:

> Unable to load addon script from path: 'res://addons/applovin_max/AppLovinMAX.gd' Base type is not EditorPlugin.

**Comment by lettdev** [comment]
Btw, this is the content of plugin.cfg in 1.0.1 release, seems like wrong file was shipped 😂

```
[plugin]

name="AppLovinMAX"
description="AppLovin MAX Godot Plugin for Android and iOS."
author="AppLovin"
version="1.0.0"
script="applovin_max.gd"
```

**Comment by christophercong** [comment]
Ahh I uploaded a fix for that yesterday on the Godot AssetLib for 1.0.1, but we have been awaiting approval. Could you try deleting your existing `res://addons/applovin_max` and replacing it with the one in this repo in the mean time?

Lesson learned 😅; we will be documenting the release/publishing process to avoid mistakes like this.

**Comment by lettdev** [comment]
> Turns out somehow the file plugin.cfg wasn't replaced and still the 1.0.0 version, which uses that file path (applovin_max.gd). I replace it now but has another error:
> 
> > Unable to load addon script from path: 'res://addons/applovin_max/AppLovinMAX.gd' Base type is not EditorPlugin.

To solve this problem, I think

```gdscript
@tool
extends EditorPlugin
```

should be added to the head of `AppLovingMAX.gd`. Now I can enable the plugin in Project Settings/Plugins 😂

**Comment by christophercong** [comment]
Ah I see. At the moment, our plugin **doesn't** require to be enabled in the `Project Settings/Plugins` as we don't perform any modifications or use any functionality in the Godot editor/IDE.

But we will someday as we add more functionality to this plugin 🙂. (edit: I can preemptively add the super-class and @tool annotation to the next release)
