### ISSUE TITLE
unable to load addon script

### ISSUE THREAD

**Issue by yan88a** [AppLovin/AppLovin-MAX-Godot#19]
### MAX Plugin Version

1.0.1

### Godot Version

4.1.1

### Device/Platform Info

android 13 - S21

### Current Behavior

following the setup instructions --> after installation, go to:
Project--> settings--> plugins--> try enable ApplovinMax1.0.1
get the following message:
"unable to load addon scipt from path: res....   base type is not editor plugin"

### Expected Behavior

to load the addon as instructed.

### How to Reproduce

after installation, go to:
Project--> settings--> plugins--> try enable ApplovinMax1.0.1

**Comment by christophercong** [comment]
Hi @yan88a, the plugin currently is not an editor plugin, it doesn't perform anything in the Godot editor/IDE. That said, I'll be updating the plugin to extend `EditorPlugin` anyway to mitigate issues.

**Comment by yan88a** [comment]
well - i thought so - that it should be an auto load instead..
in any case - i suggest to update the docs - since it points to an editor plugin enabling + the project itself parses to an "addon" dir (editor looks at it as an editor plugin)
thanks @christophercong !
