### ISSUE TITLE
No functional file when install the addon

### ISSUE THREAD

**Issue by lettdev** [AppLovin/AppLovin-MAX-Godot#3]
### MAX Plugin Version

1.0.0

### Godot Version

4.1.1

### Device/Platform Info

No

### Current Behavior

When click install, only .gitignore, README and LICENSE file are downloaded

![image](https://github.com/AppLovin/AppLovin-MAX-Godot/assets/24779254/58cbbd67-79b3-4767-8901-c77030445839)

### How to Reproduce

Install AppLovingMAX from In-Editor AssetLib

**Comment by christophercong** [comment]
Hi @lettdev, I have updated our README to include the full integration instructions for our plugin. 

It's currently a manual process, but we will be supporting In-Editor AssetLib and streamlining the process soon.
