### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by Beedevil** [AppLovin/AppLovin-MAX-Godot#32]
### MAX Plugin Version

1.0.3

### Godot Version

4.2.2

### Device/Platform Info

Xiaomi Redmi Note 9 Pro, Android 11

### Current Behavior

App crash on start

![image](https://github.com/AppLovin/AppLovin-MAX-Godot/assets/111656800/eaf30907-654d-4005-91c6-9c0f6ae4610e)
![image](https://github.com/AppLovin/AppLovin-MAX-Godot/assets/111656800/0f904e7a-697c-43d9-ad3b-24debb70a4b7)
![image](https://github.com/AppLovin/AppLovin-MAX-Godot/assets/111656800/e88b0280-50a6-4ebf-be8f-e2d8f5b59555)
![image](https://github.com/AppLovin/AppLovin-MAX-Godot/assets/111656800/f7bf942e-4278-4894-87d6-7b1fa982e92f)

### How to Reproduce

It happens to me every time

**Comment by tambunancoder** [comment]
Face same issue

**Comment by pkariuki** [comment]
I'm facing the same issue. Workload: use applovin-sdk:12.3.1

**Comment by Beedevil** [comment]
@christophercong Hello. It would be nice if we got any answer. At this point I don't know if I'm doing something wrong or if the problem is on your side? If you have decided not to develop the godot plugin further, just write about it

**Comment by lothell** [comment]
@christophercong 
I'm having the same problem, I get a crash on startup after adding `implementation 'com.applovin:applovin-sdk:+'` to dependencies in the build.gradle file.

@tambunancoder , @pkariuki , @Beedevil 
Did you ever get it running?

**Comment by tambunancoder** [comment]
> @christophercong I'm having the same problem, I get a crash on startup after adding `implementation 'com.applovin:applovin-sdk:+'` to dependencies in the build.gradle file.
> 
> @tambunancoder , @pkariuki , @Beedevil Did you ever get it running?

`implementation "com.applovin:applovin-sdk:12.3.1"`

Do not use "+".  I use this version to get it running

**Comment by thomasmso** [comment]
@christophercong can chime in, but generally speaking you need to lock the underlying native iOS/Android SDKs to the version the plugin was actually pushed against.

**Comment by lothell** [comment]
@thomasmso  @christophercong
Could you please go into detail of this? Maybe the integration guide could be updated to reflect this? I would assume this mean switching to an older godot version that the plugin was built against? I am using 4.3.

I got it working on android by specifying the version like @thomasmso suggested but I'm now having integration issues on IOS. when building in xcode I get the following error:
```

Undefined symbols for architecture arm64:
  "Object::get_argument_options(StringName const&, int, List<String, DefaultAllocator>*) const", referenced from:
      vtable for AppLovinMAXGodotPlugin in libAppLovin-MAX-Godot-Plugin.a[4](AppLovinMAXGodotPlugin.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

I hope you can help me out with this and I would love to see the integration guide expanded give some more clarity on these issues.

Thank you
