### ISSUE TITLE
Is this integration being sunset?

### ISSUE THREAD

**Issue by TinyMatt** [AppLovin/AppLovin-MAX-Godot#38]
I'm considering Godot for my next project and I'm doing research into available options when it comes to monetization.

I used MAX in my previous (unity based) project and were rather happy with it. Unfortunately the Godot plugin seems to not be maintain.

Are there any plans on supporting this project further?

**Comment by Beedevil** [comment]
Hello.

I’m also waiting to hear any updates about the official plugin's future. In the meantime, I ended up writing my own plugin for Android with AppLovin MAX for Godot 4.3 in a single day, using all the necessary adapters. The new V2 plugin system is so much simpler to work with compared to V1, and there’s even a ready-made template for Android Studio that makes creating plugins straightforward. Unfortunately, my plugin is Android-only—I haven’t explored writing plugins for iOS yet.

**Comment by TinyMatt** [comment]
@Beedevil If at any point you would consider making your work public and want some help with the iOS part, let me know!

**Comment by christophercong** [comment]
Hey all,

We are still supporting this Godot, but our engineering pipeline has been busy the last few months. Apologies for the lack of communication during this time.

We are prioritizing updates to address the issues and support Godot 4.3 before the end of the year .

Stay tuned.

**Comment by ESnider** [comment]
Yeah, very interested in this plugin also. I'm moving my game dev from iOS native and AdMob mediation to Godot 4.3. I've been... disappointed in monetization in Godot for mobile and didn't realize what the state of things was. But I'm a few months into my first game in Godot and worried about monetization now.

**Comment by lothell** [comment]
I'm looking at a Q1 release for my new project and would love to be able to use this plugin for monetization. I reallt hope you can get godot 4.3 support working soon!

**Comment by christophercong** [comment]
Hi all,

Apologies for the delay. We have released a new plugin version, 1.1.0, which adds support for Godot 4.3 and the latest AppLovinSDK major version 13.0.0+. Support for the Android V2 plugin is something we're looking at for early next year, but it should not be a blocker for now since 4.3 still supports V1.

Moving forward, we'll do better with communication and updating everyone on timelines.
