### ISSUE TITLE
AppLovinMAX =/= AppLovinMAXGodotPlugin

### ISSUE THREAD

**Issue by ESnider** [AppLovin/AppLovin-MAX-Godot#44]
### MAX Plugin Version

1.0.3

### Godot Version

4.3

### Device/Platform Info

Windows/Android

### Current Behavior

I can't tell if something is wrong in the instructions, or if there are traces of the previous non-working AppLovin plugin, or something else. I've followed the instructions as closely as possible but get warnings that the AppLovin plugin is a v1 Godot plugin and deprecated as of Godot 4.2:

    **Godot v1 plugin are deprecated in Godot 4.2 and higher: AppLovinMAX**

 I also see an error in logcat that says:

    **Meta-data plugin name does not match the value returned by the plugin handle: AppLovinMAX =/= AppLovinMAXGodotPlugin**

I'm new to Android but have many years of iOS experience. I'm not sure if there's some part of the Android build where I need to delete files to get rid of the old AppLovin library, or maybe some other meta data isn't quite right?

**Here's more of the log:**

> 
> Creating new Godot fragment instance.
> 2024-12-20 11:03:03.906  6542-6542  Godot                   pid-6542                             V  OnCreate: GodotFragment{515b577} (fba83a87-95b6-422b-bac3-9d11e911101c id=0x7f090094)
> 2024-12-20 11:03:03.906  6542-6542  Godot                   pid-6542                             V  Initializing Godot plugin registry
> 2024-12-20 11:03:03.908  6542-6542  GodotPluginRegistry     pid-6542                             W  Godot v1 plugin are deprecated in Godot 4.2 and higher: AppLovinMAX
> 2024-12-20 11:03:03.908  6542-6542  GodotPluginRegistry     pid-6542                             I  Initializing Godot plugin AppLovinMAX
> 2024-12-20 11:03:03.935  6542-6542  GodotPluginRegistry     pid-6542                             W  Meta-data plugin name does not match the value returned by the plugin handle: AppLovinMAX =/= AppLovinMAXGodotPlugin
> 2024-12-20 11:03:03.935  6542-6542  GodotPluginRegistry     pid-6542                             I  Completed initialization for Godot plugin AppLovinMAXGodotPlugin
> 

### Expected Behavior

Smooth sailing as the plugin loads and runs without errors - no warnings.

### How to Reproduce

I deleted the previously installed version at res://addons and android/plugins then followed the instructions here for Android builds: https://github.com/AppLovin/AppLovin-MAX-Godot

### Reproducible in the demo app?

Not Tested

### Additional Info

I'll try the demo app, but would appreciate if the "Download Zip" choice included the sample app instead of just the plugin.

**Comment by ESnider** [comment]
I got this working, but definitely something was wrong. I did get the example Godot project to build for Android and run etc. That worked. I believe what solved my problem was literally copying the .aar file from the example project and replacing the one that was installed via the Godot Asset Library. They were different sizes -- 79.1KB from Godot Asset Library, and the one in the example code is 65.2KB. The 65.2KB one works for me.

**Comment by ESnider** [comment]
Sorry - didn't mean to close this. I think this is worth investigating in case something's wrong with the version in Godot Asset Library.

**Comment by christophercong** [comment]
Hi @ESnider,

The version in Godot Asset Library is outdated; I submitted a new release (1.1.0) but it's still pending approval. Once that is updated, this should be resolved.

In regards to the deprecation message, that's expected. We have plans to upgrade to the new V2 android plugin system later.
