### ISSUE TITLE
3.x support

### ISSUE THREAD

**Issue by di-kang** [AppLovin/AppLovin-MAX-Godot#8]
### Feature Description

Will godot 3.x supported in the future?

Thanks for the plugin btw.

**Comment by christophercong** [comment]
Hi @di-kang, yes we do plan on supporting the LTS, 3.5.2, in the future.

**Comment by di-kang** [comment]
Great! Thank you for the quick reply. I'll be the first one to try it out when it comes out :)

**Comment by Beedevil** [comment]
I'm also waiting for a plugin for Godot 3. This is extremely important to me. Do you have any information about when we can expect it?

**Comment by christophercong** [comment]
Hi @Beedevil, since we're getting interest in Godot 3 support, I can begin work on it this week. I can update this thread as work progresses.

**Comment by christophercong** [comment]
@Beedevil @di-kang and any interested parties, would you guys mind sending your portfolio to christopher.cong@applovin.com so we can assess the opportunity/support for 3.x?

We still plan on adding 3.x support, but our engineering resources are a bit limited at the moment. I also want to understand the needs/decision behind staying with 3.x versus upgrading to 4.x; I would like to hear any insight or feedback on that if you have any.

**Comment by di-kang** [comment]
@christophercong Ok, will do.
The main reason I'm still using 3.x is that 4.x and 3.x is not compatible which means some of the plugins are not either.
And since my game is 2D, 3.x is much more reliable, at least for a while.
Also upgrading to 4.x itself isn't impossible but unfortunately right now I just don't have time to do so.

**Comment by Momo90k** [comment]
> @Beedevil @di-kang and any interested parties, would you guys mind sending your portfolio to [christopher.cong@applovin.com](mailto:christopher.cong@applovin.com) so we can assess the opportunity/support for 3.x?
> 
> We still plan on adding 3.x support, but our engineering resources are a bit limited at the moment. I also want to understand the needs/decision behind staying with 3.x versus upgrading to 4.x; I would like to hear any insight or feedback on that if you have any.

I'm not mentioned but i can tell you why it is necessary to have support for version 3.x.
1. Version 4 is still new and the majority of plugins only work with version 3
2. Version 4 removes support for many version 3 features like support for GLES2
3. Version 4 only uses Vulkan for rendering which is not supported in older computers (not all of us have the latest MacBooks)
4. Version 3 is Still widely used more than the new one

So support for version 3.x is actually **more** important.

**Comment by Momo90k** [comment]
> Hi @Beedevil, since we're getting interest in Godot 3 support, I can begin work on it this week. I can update this thread as work progresses.

Can you please give us an approximate deadline?

**Comment by Beedevil** [comment]
@christophercong Hello, how's work going? I hope you didn't give up on Godot 3?
I'll be finishing my latest android game soon and I'll be sad if I only have to use admob.
I would like to have Applovin Max and all adapters with UMP support :)

**Comment by Momo90k** [comment]
> Hi @Beedevil, since we're getting interest in Godot 3 support, I can begin work on it this week. I can update this thread as work progresses.

That's 3 months now and nothing.

**Comment by thomasmso** [comment]
@Momo90k - We've discussed internally and decided to stop engineering work on Godot 3 support. The issues and limitations faced with Godot 4 should be addressed by the Godot team, and we will need to allocate engineering resources into other items for MAX.
